version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./posts:/app/posts
      - ./out:/app/out
      - ./styles:/app/styles
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped